function dac_bit = SDM_fcn(u)  %#codegen
% Auto-generated by DESIGN_THIRD_ORDER.m
% 3rd-order CIFB sigma-delta modulator - FLOATING POINT REFERENCE
%
% This file is the floating-point golden model intended for use with
% MATLAB Fixed-Point Designer ("Convert to Fixed Point" workflow).
% All arithmetic uses double precision so the tool can instrument the
% function, observe min/max ranges, and propose data types.
%
% Input  u : signed integer count from the 13-bit ADC,
%            range [-4096, 4095]. Internally normalised to [-1,+1).
% Output : single bit (logical) for 1-bit DAC drive.
%
% Suggested starting types for Fixed-Point Designer:
%   u           : fixdt(1, 13, 0)
%   coefficients: fixdt(1, 18, 14)
%   int1..int3  : fixdt(1, 32, 14)

dac_bit = false;

persistent int1 int2 int3
if isempty(int1)
    int1 = 0;
    int2 = 0;
    int3 = 0;
end

% Floating-point coefficients (scaled CIFB, 3rd order)
B1 = 0.172222623529955;
A1 = 0.172222623529955;
A2 = 0.123562088507108;
A3 = 0.122457379474687;
C1 = 0.10952288682635;
C2 = 0.357050181625205;
G1 = 4.2457997600222e-05;

% Saturate and normalise the 13-bit signed input to [-1, +1)
u_sat = max(min(double(u), 4095), -4096);
u_norm = u_sat / 4096;

% Quantizer decision based on the last integrator (int3)
if int3 >= 0
    dac_bit = true;
    v       =  1;
else
    dac_bit = false;
    v       = -1;
end

% Integrator 1: int1 += B1*u - A1*v
int1 = int1 + B1*u_norm - A1*v;

% Integrator 2: int2 += C1*int1 - A2*v
int2 = int2 + C1*int1 - A2*v;

% Integrator 3: int3 += C2*int2 - G1*int3 - A3*v
% G1 is the resonator local feedback that places NTF zeros
% at non-DC frequencies inside the signal band.
int3 = int3 + C2*int2 - G1*int3 - A3*v;

end
